import { Inter } from "next/font/google";
import "./globals.css";
import NavbarWrapper from "@/components/NavbarWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Admin Panel | TaxClickIn",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${inter.className} text-black min-h-screen`}>
				<NavbarWrapper />
				{children}
			</body>
		</html>
	);
}
